// Сборка самодостаточного main.js:
//   вендор-библиотеки (qrcode, markdown-it) + модули рендера + код плагина.
// Использование:  node build.js /путь/к/выходному/main.js
const fs = require('fs');
const path = require('path');

const dir = __dirname;

// UMD-библиотека → module-scope переменная (fake module/exports перехватывает экспорт,
// не трогая module.exports самого плагина).
function wrapVendor(name, file) {
  const src = fs.readFileSync(path.join(dir, file), 'utf8');
  return (
    '/* vendored: ' + file + ' → ' + name + ' */\n' +
    'var ' + name + ' = (function () { var module = { exports: {} }, exports = module.exports, define;\n' +
    src + '\n;return module.exports; })();\n'
  );
}

const VENDORS = [
  ['qrcode', 'qrcode.js'],
  ['markdownit', 'markdown-it.js'],
];
const MODULES = [
  'modules/chords.js', 'modules/tasks.js', 'modules/callouts.js',
  'modules/kanban.js', 'modules/dataview.js', 'modules/excalidraw.js', 'modules/math.js',
];

let out = '/* AUTO-GENERATED by build.js — правьте src/main.js и modules/*, затем пересоберите. */\n';
for (const [name, file] of VENDORS) out += wrapVendor(name, file);
for (const f of MODULES) out += '\n/* render module: ' + f + ' */\n' + fs.readFileSync(path.join(dir, f), 'utf8') + '\n';

let code = fs.readFileSync(path.join(dir, 'main.js'), 'utf8').replace(/^'use strict';\s*\n/, '');
out += '\n/* ===== plugin ===== */\n' + code;

const target = process.argv[2] || path.join(dir, 'dist', 'main.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out);
console.log('wrote', target, out.length, 'bytes');
